version: "3.8"

services:
  dbtest:
    image: postgres:latest
    env_file: ./config/.env

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file: ./config/.env
    volumes:
      - ".:/code/"
    depends_on:
      - dbtest
    entrypoint: []
    restart: always
