"""initial_migration

Revision ID: 0001
Revises: 
Create Date: 2024-10-13 13:18:49.778372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cl_task_status',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Наименование статуса'),
    sa.PrimaryKeyConstraint('id'),
    comment='Модель статуса задачи.'
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Идентификатор'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Почта'),
    sa.Column('first_name', sa.String(length=100), nullable=True, comment='Имя'),
    sa.Column('second_name', sa.String(length=100), nullable=True, comment='Фамилия'),
    sa.Column('middle_name', sa.String(length=100), nullable=True, comment='Отчество'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Имя пользователя'),
    sa.Column('_password_hash', sa.String(), nullable=False, comment='Хеш пароля'),
    sa.PrimaryKeyConstraint('id'),
    comment='Модель пользователя.'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Идентификатор'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Заголовок задачи'),
    sa.Column('description', sa.String(), nullable=False, comment='Описание задачи'),
    sa.Column('task_status_id', sa.Integer(), nullable=False, comment='Идентификатор статуса'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Создана'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Обновлена'),
    sa.Column('complete_before', sa.DateTime(), nullable=True, comment='Выполнить до'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Выполнена'),
    sa.ForeignKeyConstraint(['task_status_id'], ['cl_task_status.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Модель задачи.'
    )
    op.create_index(op.f('ix_tasks_task_status_id'), 'tasks', ['task_status_id'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_status_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('cl_task_status')
    # ### end Alembic commands ###
