"""data_migration

Revision ID: 0002
Revises: 0001
Create Date: 2024-09-26 09:12:44.556295

"""
from os import path
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    files_names = [
        'cl_task_status.sql'
    ]
    for file_name in files_names:
        with open(path.join('data', file_name), 'r') as file:
            op.execute(file.read())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE cl_task_status RESTART IDENTITY CASCADE;')
    # ### end Alembic commands ###
